## NumPy

In [2]:
import numpy as np

### Arreglos

In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
arr = np.array(([1,2,3], [4, 5, 6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array(([1,2,3], [4, 5, 6], [7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
arr = np.array([1,2,3,4,5,6], ndmin=3)
print(arr.ndim)
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])

3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [6]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [7]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
arr = np.random.rand(3,3)
print(arr)

[[0.41810641 0.77444742 0.8198509 ]
 [0.09900127 0.22392393 0.1474155 ]
 [0.71139457 0.46970693 0.24119259]]


## Operaciones

In [9]:
arr1 = [1,2,3]
arr2 = [4,5,6]

arr3 = np.add(arr1, arr2)
print(arr3)

[5 7 9]


In [11]:
arr2 = [1,2,3]
arr1 = [4,5,6]

arr3 = np.subtract(arr1,arr2)
print(arr3)

[3 3 3]


In [13]:
arr1 = [1,2,3]
arr2 = [4,5,6]

arr3 = np.multiply(arr1, arr2)
print(arr3)

[ 4 10 18]


In [14]:
arr1 = [1,2,3]
arr2 = [4,5,6]

arr3 = np.divide(arr1, arr2)
print(arr3)

[0.25 0.4  0.5 ]


## Agregacion

In [17]:
arr = [1, 5, 7]
media = np.mean(arr)
print(media)

4.333333333333333


In [18]:
arr = [1, 5, 7]
median = np.median(arr)
print(median)

5.0


In [19]:
arr = [1, 5, 7]
max = np.max(arr)
print(max)

7


In [20]:
arr = [1, 5, 7]
min = np.min(arr)
print(min)

1


## Indexacion

In [21]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])

1


In [22]:
arr = np.array([1,2,3,4,5,6])
print(arr[-1])

6


In [25]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr[1,2])

6


## Slicing

In [26]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [28]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4:2])

[2 4]


In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr[::2])

[1 3 5]


## Tipo de Datos

In [1]:
import numpy as np
arr = np.array(["b","a"])
print(arr.dtype)

<U1


In [3]:
arr = np.array([1.3, 2.5])
print(arr.dtype)

float64


## Copy vs View

## Pamdas

## CSV

In [5]:
import pandas as pd
df = pd.read_csv('C:\\Users\\hj5k5r\\Python 3 Curso\\Perfil de estudiante.csv')
print(df.to_string())

                     Marca temporal                        1.- ¿De dónde eres? 2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas? 5.- ¿Cuál es tu nivel de conocimiento en Python?                                           6.- ¿Qué tema relacionado con Python te gustaría aprender? 7.- ¿Has participado en algún curso anteriormente en el IA Center?                             8.- ¿Cuál es tu canción favorita?
0    2023/06/27 7:42:12 p. m. GMT-6                                 Cd. Juárez             Entre 21 y 24             Sí             No                                           Básico                                                                               Manejar bases de datos                                                                 No                                                      The Wolf
1    2023/06/27 7:42:28 p. m. GMT-6                       chihuahua, chihuahua             Entre 21 y 24             Sí             Sí                                      

In [6]:
df.head()

Marca temporal   1.- ¿De dónde eres?  \
0  2023/06/27 7:42:12 p. m. GMT-6            Cd. Juárez   
1  2023/06/27 7:42:28 p. m. GMT-6  chihuahua, chihuahua   
2  2023/06/27 7:42:44 p. m. GMT-6   Chihuahua Chihuahua   
3  2023/06/27 7:42:52 p. m. GMT-6   Chihuahua Chihuahua   
4  2023/06/27 7:42:56 p. m. GMT-6      Chihuahua, Chih.   

  2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
0             Entre 21 y 24             Sí             No   
1             Entre 21 y 24             Sí             Sí   
2             Entre 18 y 20             Sí             Sí   
3             Entre 21 y 24             Sí             Sí   
4                 Más de 30             No             Sí   

  5.- ¿Cuál es tu nivel de conocimiento en Python?  \
0                                           Básico   
1                                           Básico   
2                                           Básico   
3                                           Básico   
4                                           Básico   

  6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
0                             Manejar bases de datos           
1                                    machine lerning           
2      Automatización y creación de apps/páginas web           
3                                  Análisis de datos           
4                              Conocer más librerias           

  7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
0                                                 No                   
1                                                 Sí                   
2                                                 No                   
3                                                 Sí                   
4                                                 Sí                   

  8.- ¿Cuál es tu canción favorita?  
0                          The Wolf  
1                   eternity, anyma  
2    Cornerstone- Arctic Monkeys :)  
3                   Sea Gets Hotter  
4        Love Me More, de Sam Smith

In [7]:
df.tail()

Marca temporal                1.- ¿De dónde eres?  \
38  2023/06/27 10:02:11 p. m. GMT-6                Ciudad Juarez, Chih   
39  2023/06/27 10:31:28 p. m. GMT-6                          cd juarez   
40  2023/06/28 10:12:04 p. m. GMT-6                          Chihuahua   
41   2023/06/29 2:00:51 a. m. GMT-6  Vivo en Ciudad Juárez. Soy cubana   
42   2023/07/03 1:55:24 p. m. GMT-6                      Ciudad Juarez   

   2.- ¿Cuántos años tienes? 3.- ¿Estudias? 4.- ¿Trabajas?  \
38             Entre 21 y 24             No             Sí   
39             Entre 21 y 24             Sí             Sí   
40             Entre 21 y 24             No             Sí   
41                 Más de 30             Sí             No   
42                 Más de 30             No             Sí   

   5.- ¿Cuál es tu nivel de conocimiento en Python?  \
38                                           Básico   
39                                           Básico   
40                                           Básico   
41                                       Intermedio   
42                                       Intermedio   

   6.- ¿Qué tema relacionado con Python te gustaría aprender?  \
38                                  Analisis de datos           
39                                           punteros           
40                   Machine Learning y Deep Learning           
41  Cómo escribir un código de forma profesional, ...           
42                                     Automatizacion           

   7.- ¿Has participado en algún curso anteriormente en el IA Center?  \
38                                                 Sí                   
39                                                 Sí                   
40                                                 Sí                   
41                                                 No                   
42                                                 No                   

                    8.- ¿Cuál es tu canción favorita?  
38                       https://youtu.be/BGVUiMskx_U  
39                             porter guiame quetzal   
40                                            Runaway  
41  Hay varias, pero últimamente escucho mucho "Cu...  
42                              David Bowie - Heroes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 9 columns):
 #   Column                                                              Non-Null Count  Dtype 
---  ------                                                              --------------  ----- 
 0   Marca temporal                                                      43 non-null     object
 1   1.- ¿De dónde eres?                                                 43 non-null     object
 2   2.- ¿Cuántos años tienes?                                           43 non-null     object
 3   3.- ¿Estudias?                                                      43 non-null     object
 4   4.- ¿Trabajas?                                                      43 non-null     object
 5   5.- ¿Cuál es tu nivel de conocimiento en Python?                    43 non-null     object
 6   6.- ¿Qué tema relacionado con Python te gustaría aprender?          43 non-null     object
 7   7.- ¿Has participado en algún

## JSON

In [10]:
df = pd.read_json('C:\\Users\\hj5k5r\\Python 3 Curso\\dataset.json')
print(df.to_string())

                                                 personas
0      {'nombre': 'Juan', 'edad': 25, 'ciudad': 'Madrid'}
1  {'nombre': 'María', 'edad': 30, 'ciudad': 'Barcelona'}
2   {'nombre': 'Pedro', 'edad': 35, 'ciudad': 'Valencia'}


In [17]:
data = {

    'Nombre': ['Juan', 'María', 'Pedro', 'Ana', 'Luis'],
    'Edad': [25, 32, None, 42, 28],
    'Fecha': ['31/01/2020', '31/01/2020', None, '31/01/2020', '01/31/2020'],
    'Género': ['M', 'F', None, 'F', 'M'],
    'Ciudad': ['Madrid', None, 'Madrid', 'Valencia', 'Barcelona'],
    'Altura': [175, 163, 180, 158, 170],
    'Peso': [70, None, 80, 60, 75],
    'Ingresos': [50000, 60000, 40000, None, 55000]
}

In [25]:
df = pd.DataFrame(data)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [15]:
df_sin_vacios = df.dropna()
print(df_sin_vacios.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [16]:
df.dropna(inplace=True)
print(df.to_string())

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [19]:
df.fillna("Sin registro", inplace=True)
print(df)

  Nombre          Edad         Fecha        Género        Ciudad  Altura  \
0   Juan          25.0    31/01/2020             M        Madrid     175   
1  María          32.0    31/01/2020             F  Sin registro     163   
2  Pedro  Sin registro  Sin registro  Sin registro        Madrid     180   
3    Ana          42.0    31/01/2020             F      Valencia     158   
4   Luis          28.0    01/31/2020             M     Barcelona     170   

           Peso      Ingresos  
0          70.0       50000.0  
1  Sin registro       60000.0  
2          80.0       40000.0  
3          60.0  Sin registro  
4          75.0       55000.0  


In [21]:
df["Ingresos"].fillna(0, inplace=True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       0.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [22]:
media = df["Ingresos"].mean()
print(media)

41000.0


In [24]:
df["Ingresos"].fillna(media,inplace=True)
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0   41000.0
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [26]:
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163   NaN   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0


In [29]:
mode_fecha = df["Fecha"].mode()
media_edad = df["Edad"].mean()
mode_ciudad = df["Ciudad"].mode()
media_peso = df["Peso"].mean()
media_ingresos = df["Ingresos"].mean()

In [30]:
df.loc[1, "Peso"] = 70
print(df)

  Nombre  Edad       Fecha Género     Ciudad  Altura  Peso  Ingresos
0   Juan  25.0  31/01/2020      M     Madrid     175  70.0   50000.0
1  María  32.0  31/01/2020      F       None     163  70.0   60000.0
2  Pedro   NaN        None   None     Madrid     180  80.0   40000.0
3    Ana  42.0  31/01/2020      F   Valencia     158  60.0       NaN
4   Luis  28.0  01/31/2020      M  Barcelona     170  75.0   55000.0
